# plugin: constructed
# strict: false

# groups:
#   # Simple groups that will definitely work
#   ubuntu_prod_vms: "'ubuntu' in (tags | default([]))"
#   windows_prod_vms: "'windows' in (tags | default([]))"  
#   redhat_prod_vms: "'redhat' in (tags | default([]))"

# compose:
#   ansible_host: guest.ipAddress | default(inventory_hostname)
#   ansible_user: >-
#     {{ 'Administrator' if 'windows' in (tags | default([])) else 'brine' }}
#   ansible_connection: >-
#     {{ 'winrm' if 'windows' in (tags | default([])) else 'ssh' }}