plugin: constructed
strict: false
compose:
  ansible_host: public_ipv4_addresses[0]

groups:
  ubuntu_prod_vms: "'Ubuntu' in tags.OS and tags.Env == 'prod'"
  rhel_prod_vms: "'RHEL' in tags.OS and tags.Env == 'prod'"
  windows_prod_vms: "'Windows' in tags.OS and tags.Env == 'prod'"
