# plugin: gcp_compute
# projects:
#   - poc-project-463913
# auth_kind: serviceaccount
# service_account_file: ~/gcp-key.json
# zones:
#   - us-east1-b


# # Only include running instances
# filters:
#   - status = RUNNING

# keyed_groups:
#   - prefix: label
#     key: labels.env

# hostnames:
#   - public_ip

# # Group by labels 
# groups:
#   ubuntu_prod_vms: "'ubuntu' in labels.os and labels.env == 'prod'"
#   redhat_prod_vms: "'rhel' in labels.os and labels.env == 'prod'"  
#   windows_prod_vms: "'windows' in labels.os and labels.env == 'prod'"
  


# ✅ RECOMMENDATION TO TEAM:
# Ensure that all deployed VMs are labeled appropriately, especially with an 'env' label
# (e.g., env=dev, env=qa, env=prod). This enables reliable grouping and targeting
# for configuration management and automation tasks in Ansible.
#
# Labeling based on environment helps separate dev/test/staging/prod resources, avoids accidental cross-env changes,
# and improves reporting, auditing, and governance across GCP resources.
