plugin: oracle.oci.oci
regions:
  - us-ashburn-1  # Change to your OCI region
compartments:
  - compartment_ocid: "{{ compartment_ocid }}"  # Will be read from vars or env
instance_principal_authentication: false
config_file: ~/.oci/config  # Path to your OCI config file
config_profile: DEFAULT

keyed_groups:
  - prefix: tag
    key: freeform_tags
    separator: "_"

groups:
  # Group by instance state
  running: instance_lifecycle_state == "RUNNING"

compose:
  ansible_host: public_ip | default(private_ip)

---