plugin: vmware_vm_inventory
strict: False
hostname: emea-sa-vcenter.bbn.is.keysight.com
username: brine@sa.lab
password: Brave123.
datacenter: DC
cluster: Production
validate_certs: False
with_tags: True

# Properties to fetch from vCenter
properties:
  - name
  - runtime.powerState
  - guest.ipAddress

# Use VM name as hostname instead of the long ID
hostnames:
  - name

# Set ansible_host to the IP address
compose:
  ansible_host: guest.ipAddress

# Keyed groups - automatically create groups based on VM properties
keyed_groups:
  # Group by power state
  - key: runtime.powerState
    prefix: power_state
    separator: '_'
  
  # Group by guest OS ID
  - key: config.guestId
    prefix: os
    separator: '_'