# ========================================
# VMware vCenter Configuration
# ========================================
vcenter_hostname: "emea-sa-vcenter.bbn.is.keysight.com"
vcenter_username: "brine@sa.lab"
vcenter_password: "Brave123."
vcenter_datacenter: "DC"
vcenter_cluster: "Production"

# ========================================
# General CloudLens Configuration
# ========================================
cloudlens_manager_ip_or_FQDN: "52.232.181.182"
project_key: "4d20025297414f7ab840a6e9086de116"
custom_tags: "Env=VMware Region=OnPrem"
cloudlens_agent_container_name: "cloudlens-agent"

# ========================================
# Registry Configuration
# ========================================
registry_type: "insecure"
local_ca_path: "/Users/brinketu/NewCerts/cloudlenscerts.crt"
ca_cert_dir: "/etc/ssl/certs"

# ========================================
# Log Rotation Settings
# ========================================
log_max_size: "50m"
log_max_file: "5"


# VMware Tools settings
vmware_tools_install: true