# General CloudLens Configuration
cloudlens_manager_ip_or_FQDN: "35.86.201.194"
project_key: "6a357a17676c4863856970d40e65d7c5"
custom_tags: "Env= AWS Region= US-WEST-2"
cloudlens_agent_container_name: "cloudlens-agent"



# Registry Configuration
registry_type: "insecure"  # Set to "secure" if you're using a signed registry
local_ca_path: "/Users/brinketu/NewCerts/cloudlenscerts.crt"  # Full cert chain (for secure registry)
ca_cert_dir: "/etc/ssl/certs"
ansible_connection: ssh



# Log Rotation Settings
log_max_size: "50m"                            
log_max_file: "5"


# Windows Deployment
local_installer_path: "/Users/brinketu/Downloads/cloudlens-win-sensor-6.11.1.302.exe"
cloudlens_installer_filename: "cloudlens-win-sensor-6.11.1.302.exe"
ssl_verify: "no"      # Set to "yes" if using secure SSL cert
auto_update: "yes"



# Python interpreter for RHEL/CentOS/ubuntu (important for Ansible to work correctly)
# ansible_python_interpreter: /usr/bin/python3 
# ansible_python_interpreter: /usr/libexec/platform-python
# Replace if dir or custom python interpreter is used. Refer to 
# Ansible interpreter discovery reference:( ignore warning)
# https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html

